# Generated by Django 2.2.5 on 2019-10-23 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testperm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
