# Generated by Django 2.2.5 on 2019-10-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testperm', '0003_auto_20191023_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
